<?php

namespace common\models;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "complexes".
 *
 * @property int $id
 * @property string|null $address
 * @property int|null $city_id
 * @property int|null $region_id
 * @property string|null $description_tr
 * @property string|null $description_ru
 * @property string|null $description_en
 * @property int|null $count_buildings
 * @property int|null $count_storeys
 * @property int|null $created_at
 * @property int|null $updated_at
 * @property int|null $created_by
 * @property int|null $updated_by
 * @property int|null $type_id
 * @property string|null $title_tr
 * @property string|null $title_ru
 * @property string|null $title_en
 *
 * @property Apartments[] $apartments
 * @property ComplexImages[] $complexImages
 * @property ComplexOptions[] $complexOptions
 * @property Tags[] $tags
 * @property TypeFlat $type
 * @property Cities $city
 * @property Regions $region
 */
class Complexes extends \yii\db\ActiveRecord
{

    public $tag_ids;
    public $images;
    public $options;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'complexes';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['address', 'description_tr', 'description_ru', 'description_en', 'title_tr','title_ru','title_en'], 'string'],
            [['city_id', 'region_id', 'created_at', 'updated_at', 'created_by', 'updated_by','count_buildings', 'count_storeys',], 'integer'],
            [['tag_ids','images','options'], 'safe'],
            [['address','city_id','region_id','address', 'description_tr', 'description_ru', 'description_en', 'title_tr','title_ru','title_en','type_id','count_buildings','count_storeys'], 'required'],
        ];
    }

    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
            BlameableBehavior::className()
        ]; // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'address' => 'Address',
            'city_id' => 'City ID',
            'region_id' => 'Region ID',
            'description_tr' => 'Description Tr',
            'description_ru' => 'Description Ru',
            'description_en' => 'Description En',
            'count_buildings' => 'Count Buildings',
            'count_storeys' => 'Count Storeys',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
            'title_tr' => 'Title tr',
            'title_ru' => 'Title ru',
            'title_en' => 'Title en',
        ];
    }

    /**
     * Gets query for [[Apartments]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getApartments()
    {
        return $this->hasMany(Apartments::class, ['complex_id' => 'id']);
    }

    /**
     * Gets query for [[ComplexImages]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getComplexImages()
    {
        return $this->hasMany(ComplexImages::class, ['complex_id' => 'id']);
    }
    /**
     * Gets query for [[ComplexOptions]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getComplexOptions()
    {
        return $this->hasMany(ComplexOptions::class, ['complex_id' => 'id']);
    }
    /**
     * Gets query for [[ComplexOptions]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getTags()
    {
        return $this->hasMany(Tags::class, ['id' => 'tag_id'])->viaTable('complex_tags',['complex_id'=>'id']);
    }

    public function getType()
    {
        return $this->hasOne(TypeFlat::class,['id' => 'type_id']);
    }
    public function getCity()
    {
        return $this->hasOne(Cities::class,['id' => 'city_id']);
    }
    public function getRegion()
    {
        return $this->hasOne(Regions::class,['id' => 'region_id']);
    }


    public function afterSave($insert, $changedAttributes)
    {

        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

}
