<?php

namespace common\models;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "option_values".
 *
 * @property int $id
 * @property int|null $option_id
 * @property string|null $value_tr
 * @property string|null $value_ru
 * @property string|null $value_en
 * @property string|null $icon
 * @property int|null $weight
 * @property int|null $created_at
 * @property int|null $updated_at
 *
 * @property Options $option
 */
class OptionValues extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'option_values';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['option_id', 'weight', 'created_at', 'updated_at'], 'integer'],
            [['value_tr', 'value_ru', 'value_en', 'icon'], 'string', 'max' => 255],
            [['option_id'], 'exist', 'skipOnError' => true, 'targetClass' => Options::class, 'targetAttribute' => ['option_id' => 'id']],
        ];
    }

    public function behaviors()
    {
        return [
            TimestampBehavior::className()
        ]; // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'option_id' => 'Option ID',
            'value_tr' => 'Value Tr',
            'value_ru' => 'Value Ru',
            'value_en' => 'Value En',
            'icon' => 'Icon',
            'weight' => 'Weight',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * Gets query for [[Option]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getOption()
    {
        return $this->hasOne(Options::class, ['id' => 'option_id']);
    }
}
