<?php

namespace common\models;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "team".
 *
 * @property int $id
 * @property string|null $name_tr
 * @property string|null $name_en
 * @property string|null $name_ru
 * @property string|null $prof_ru
 * @property string|null $prof_tr
 * @property string|null $prof_en
 * @property string|null $phone
 * @property string|null $email
 * @property string|null $google
 * @property string|null $facebook
 * @property string|null $instagram
 * @property string|null $telegram
 * @property string|null $img
 * @property int|null $updated_at
 * @property int|null $created_at
 */
class Team extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'team';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['updated_at', 'created_at'], 'integer'],
            [['name_tr', 'name_en', 'name_ru', 'prof_ru', 'prof_tr', 'prof_en', 'phone', 'email', 'google', 'facebook', 'instagram', 'telegram','img'], 'string', 'max' => 255],
        ];
    }


    public function behaviors()
    {
        return [
            TimestampBehavior::className()
        ]; // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name_tr' => 'Name Tr',
            'name_en' => 'Name En',
            'name_ru' => 'Name Ru',
            'prof_ru' => 'Prof Ru',
            'prof_tr' => 'Prof Tr',
            'prof_en' => 'Prof En',
            'phone' => 'Phone',
            'email' => 'Email',
            'google' => 'Google',
            'facebook' => 'Facebook',
            'instagram' => 'Instagram',
            'telegram' => 'Telegram',
            'img' => 'Image',
            'updated_at' => 'Updated At',
            'created_at' => 'Created At',
        ];
    }
}
