<?php

namespace backend\models\sliders;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "sliders".
 *
 * @property int $id
 * @property string $key
 * @property string $name
 * @property int $status
 * @property int $created_at
 * @property int $updated_at
 *
 * @property SliderItems[] $sliderItems
 */
class Sliders extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'sliders';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['key', 'name'], 'required'],
            [['status', 'created_at', 'updated_at'], 'integer'],
            [['key', 'name'], 'string', 'max' => 64],
            [['key'], 'unique'],
        ];
    }


    public function behaviors()
    {
        return [
            TimestampBehavior::className()
        ]; // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'key' => 'Key',
            'name' => 'Name',
            'status' => 'Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * Gets query for [[SliderItems]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getSliderItems()
    {
        return $this->hasMany(SliderItems::class, ['slider_id' => 'id']);
    }



    /**
     *
     * STATUS
     *
     */

    const STATUS_ACTIVE = 10;
    const STATUS_NOT_ACTIVE = -10;

    public static function getStatusList($status=null)
    {
        $array = [
            self::STATUS_ACTIVE => 'Active',
            self::STATUS_NOT_ACTIVE => 'Not Active',

        ];

        return $status == null?$array:$array[$status];
    }


    public function getStatusName()
    {
        $array = [
            self::STATUS_ACTIVE => self::getStatusList(self::STATUS_ACTIVE),
            self::STATUS_NOT_ACTIVE => self::getStatusList(self::STATUS_NOT_ACTIVE),
        ];

        return $this->status != null ? $array[$this->status]:null;
    }
}
